/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel_Management_System;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author hossam
 */
public class Hotel_System extends javax.swing.JFrame {

    /**
     * Creates new form Hotel_System
     */
    public Hotel_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerRef = new javax.swing.JLabel();
        Firstname = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        Surname = new javax.swing.JLabel();
        PostCode = new javax.swing.JLabel();
        Meal = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        customerMo = new javax.swing.JLabel();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtCustomerRef = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtPostCode = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtcustomerMo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        RmNo = new javax.swing.JLabel();
        RMType = new javax.swing.JLabel();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        RmExt = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        Tax = new javax.swing.JLabel();
        SubTotal = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jbtnTotalCost = new javax.swing.JButton();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        JbtnResat = new javax.swing.JButton();
        JbtnExit = new javax.swing.JButton();
        JbtnDelete = new javax.swing.JButton();
        JbtnUpdate = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jCobRmExt = new javax.swing.JComboBox<>();
        jCobRMType = new javax.swing.JComboBox<>();
        jCobRmNo = new javax.swing.JComboBox<>();
        jCobMeal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomerRef.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerRef.setText("Custome_Rrf:");
        getContentPane().add(CustomerRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Firstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Firstname.setText("Firstname:");
        getContentPane().add(Firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        Address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Address.setText("Address1:");
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        Surname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Surname.setText("Surname:");
        getContentPane().add(Surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        PostCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PostCode.setText("PostCode:");
        getContentPane().add(PostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        Meal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Meal.setText("Meal:");
        getContentPane().add(Meal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Email.setText("Email:");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        customerMo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerMo.setText("Cust Mobile:");
        getContentPane().add(customerMo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 140, -1));

        jtxtCustomerRef.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtCustomerRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 140, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 140, -1));

        jtxtSurname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 140, -1));

        jtxtPostCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, -1));

        jtxtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 140, -1));

        jtxtcustomerMo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtcustomerMo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nationality:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Data of Birth:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Gender:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("ID Type:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("CheckoutDate:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Check InDate:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        RmNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RmNo.setText("Room No:");
        getContentPane().add(RmNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        RMType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RMType.setText("Room Type:");
        getContentPane().add(RMType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));
        getContentPane().add(jLocaleChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 140, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Custome_Rrf", "Firstname", "Surname", "Address1", "PostCode", "Cust Mobile", "Email", "Nationality", "Date of Birth", "Gender", "Check InDate", "CheckoutDate", "Meal", "Room Type", "Room No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 870, 500));

        RmExt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RmExt.setText("Room EXT.No:");
        getContentPane().add(RmExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 140, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 140, -1));
        getContentPane().add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 140, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Tax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tax.setText("Tax:");

        SubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubTotal.setText("SubTotal:");

        Total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Total.setText("Total:");

        jbtnTotalCost.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnTotalCost.setText("TotalCost");
        jbtnTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalCostActionPerformed(evt);
            }
        });

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        JbtnResat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JbtnResat.setText("Reset");
        JbtnResat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnResatActionPerformed(evt);
            }
        });

        JbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JbtnExit.setText("Exit");
        JbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnExitActionPerformed(evt);
            }
        });

        JbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JbtnDelete.setText("Delete");
        JbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDeleteActionPerformed(evt);
            }
        });

        JbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JbtnUpdate.setText("Update");
        JbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tax)
                    .addComponent(SubTotal)
                    .addComponent(Total))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(JbtnResat, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(JbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tax)
                            .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JbtnResat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1130, 120));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 140, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ID Type", "Driving Licence", "Passport", "Pilot Licence", "Student ID" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 140, -1));

        jCobRmExt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCobRmExt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Ext No", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112" }));
        getContentPane().add(jCobRmExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 140, -1));

        jCobRMType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCobRMType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room Type", "Single", "Double", "Family" }));
        jCobRMType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCobRMTypeActionPerformed(evt);
            }
        });
        getContentPane().add(jCobRMType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 140, -1));

        jCobRmNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCobRmNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room No", "001", "002", "003", "004", "005", "006", "007", "008", "009", "010", "011", "012" }));
        getContentPane().add(jCobRmNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 140, -1));

        jCobMeal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select No.of meal", "1", "2", "3" }));
        getContentPane().add(jCobMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 140, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void JbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnExitActionPerformed
        // TODO add your handling code here:
        frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "confirm if you want to exit", "Hotel Management System", 
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
        System.exit(0);
        
        
        }
            
            
            
        
        
            
            
            
            
        
        
        
    }//GEN-LAST:event_JbtnExitActionPerformed

    private void JbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model= (  DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
        
       if(jTable1.getRowCount()==0){
        
         JOptionPane.showMessageDialog(null,"Hotel Booking Update Confirmed","Hotel Management System",JOptionPane.OK_OPTION);
         
        
        }
       else{
       JOptionPane.showMessageDialog(null,"Select a row to delete ","Hotel Management System",JOptionPane.OK_OPTION);
       
       }
        }
       else{
               
               model.removeRow(jTable1.getSelectedRow());
               
              
        
        
        }
        
                
        
        
        
        
    }//GEN-LAST:event_JbtnDeleteActionPerformed

    private void JbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnUpdateActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model= (  DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
        
       if(jTable1.getRowCount()==0){
        
         JOptionPane.showMessageDialog(null,"Hotel Booking Update Confirmed","Hotel Management System",JOptionPane.OK_OPTION);
         
        
        }
        
        
        }
    }//GEN-LAST:event_JbtnUpdateActionPerformed

    
    private void JbtnResatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnResatActionPerformed
    DefaultTableModel model= (  DefaultTableModel)jTable1.getModel();
    model.setRowCount(0);
    
  jtxtCustomerRef.setText(null);
   jtxtFirstname.setText(null);
   jtxtSurname.setText(null);
   jtxtAddress.setText(null);
   jtxtEmail.setText(null);
   jtxtPostCode.setText(null);
   jtxtcustomerMo.setText(null);
   jtxtAddress.setText(null);
   jDateChooser1.setDate(null);
   jDateChooser2.setDate(null);
   jDateChooser3.setDate(null);
   jCobMeal.setSelectedIndex(0);
   jCobRMType.setSelectedIndex(0);
   jCobRmNo.setSelectedIndex(0);
   jCobRmExt.setSelectedIndex(0);

    
    
    }//GEN-LAST:event_JbtnResatActionPerformed

    private void jbtnTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalCostActionPerformed
  
          int SingleRoom=35;
        int DoubleRoom=55;
        int FamilyRoom=55;
        
        int oneMeal=7;
        int twoMeals=55;
        int threeMeals=55;
        SimpleDateFormat format=new SimpleDateFormat("yyyy_mm_dd");
         Date Check_In_Date=null;
         Date Check_Out_Date=null;
         try{
         Check_In_Date= format.parse(format.format(jDateChooser3.getDate()));
          Check_In_Date= format.parse(format.format(jDateChooser2.getDate()));
         }
         catch(Exception e){
         e.printStackTrace();
         }
             long Checkdiff=Check_In_Date.getTime()-Check_Out_Date.getTime();

             int Daysdiff=(int)(Checkdiff/1000/60/60/24);
             if(jCobRMType.getSelectedItem().equals("Single")&&jCobMeal.getSelectedItem().equals("1")){
             
             jtxtTotal.setText(Integer.toString(Daysdiff*SingleRoom)+oneMeal);
             jtxtTax.setText(Integer.toString(Daysdiff*SingleRoom)+oneMeal);
             jtxtSubTotal.setText(Integer.toString(Daysdiff*SingleRoom)+oneMeal);
             
             double q =Double.parseDouble(jtxtTax.getText());

             q=(q*0.25)/100;
             String tax=String.format(("آ£ %.2f"), q);
             jtxtTax.setText(tax);
            double st =Double.parseDouble(jtxtSubTotal.getText());
            st=(st);
             String subtotal=String.format(("آ£ %.2f"), st);
             jtxtSubTotal.setText(subtotal);
             double tt =Double.parseDouble(jtxtTotal.getText());
             tt=(tt);

             String total=String.format(("آ£ %.2f"), tt+q);
             jtxtTotal.setText(total);
             }
             else if (jCobRMType.getSelectedItem().equals("Double")&&jCobMeal.getSelectedItem().equals("1")){
             
             jtxtTotal.setText(Integer.toString(Daysdiff*DoubleRoom)+oneMeal);
             jtxtTax.setText(Integer.toString(Daysdiff*DoubleRoom)+oneMeal);
             jtxtSubTotal.setText(Integer.toString(Daysdiff*DoubleRoom)+oneMeal);
             
             double q =Double.parseDouble(jtxtTax.getText());

             q=(q*0.25)/100;
             String tax=String.format(("آ£ %.2f"), q);
             jtxtTax.setText(tax);
            double st =Double.parseDouble(jtxtSubTotal.getText());
             String subtotal=String.format(("آ£ %.2f"), st);
             jtxtSubTotal.setText(subtotal);
             double tt =Double.parseDouble(jtxtTotal.getText());

             String total=String.format(("آ£ %.3f"), tt+q);
             jtxtTotal.setText(total);
             }
             else         if(jCobRMType.getSelectedItem().equals("Family")&&jCobMeal.getSelectedItem().equals("1")){
             
             jtxtTotal.setText(Integer.toString(Daysdiff*FamilyRoom)+oneMeal);
             jtxtTax.setText(Integer.toString(Daysdiff*FamilyRoom)+oneMeal);
             jtxtSubTotal.setText(Integer.toString(Daysdiff*FamilyRoom)+oneMeal);
             
             double q =Double.parseDouble(jtxtTax.getText());

             q=(q*0.25)/100;
             String tax=String.format(("آ£ %.2f"), q);
             jtxtTax.setText(tax);
            double st =Double.parseDouble(jtxtSubTotal.getText());
             String subtotal=String.format(("آ£ %.2f"), st);
             jtxtSubTotal.setText(subtotal);
             double tt =Double.parseDouble(jtxtTotal.getText());

             String total=String.format(("آ£ %.2f"), tt+q);
             jtxtTotal.setText(total);
             }
      
        DefaultTableModel model= (  DefaultTableModel)jTable1.getModel();
    model.addRow(new Object[]{
    
    
  jtxtCustomerRef.getText(),
   jtxtFirstname.getText(),
   jtxtSurname.getText(),
   jtxtAddress.getText(),
   jtxtEmail.getText(),
   jtxtPostCode.getText(),
   jtxtcustomerMo.getText(),
   jtxtAddress.getText(), 
   jLocaleChooser1.getSelectedIndex(),
   jDateChooser1.getDate(),
   jDateChooser2.getDate(),
   jDateChooser3.getDate(),
   jCobMeal.getSelectedIndex(),
   jCobRMType.getSelectedIndex(),
   jCobRmNo.getSelectedIndex(),
   jCobRmExt.getSelectedIndex(),
    });
    }//GEN-LAST:event_jbtnTotalCostActionPerformed

    private void jCobRMTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCobRMTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCobRMTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel CustomerRef;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Firstname;
    private javax.swing.JButton JbtnDelete;
    private javax.swing.JButton JbtnExit;
    private javax.swing.JButton JbtnResat;
    private javax.swing.JButton JbtnUpdate;
    private javax.swing.JLabel Meal;
    private javax.swing.JLabel PostCode;
    private javax.swing.JLabel RMType;
    private javax.swing.JLabel RmExt;
    private javax.swing.JLabel RmNo;
    private javax.swing.JLabel SubTotal;
    private javax.swing.JLabel Surname;
    private javax.swing.JLabel Tax;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel customerMo;
    private javax.swing.JComboBox<String> jCobMeal;
    private javax.swing.JComboBox<String> jCobRMType;
    private javax.swing.JComboBox<String> jCobRmExt;
    private javax.swing.JComboBox<String> jCobRmNo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnTotalCost;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtCustomerRef;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtcustomerMo;
    // End of variables declaration//GEN-END:variables
}
